### ISSUE TITLE
PSS: drawn line coordinates and body coordinates do not line up

### ISSUE THREAD

**Issue by niebl** [niebl/BTDS-project#12]
There is a strong incongruity between the drawn line and the body within the monitoring view of the PSS.
At this point we don't know what could be causing this.

It is vital that the coordinates of the drawn line do line up with the coordinates of the detected bodies

**Comment by niebl** [comment]
I made some experimentation with 2 cases:
1. line drawn roughly at spine height on location of body
2. 
![image](https://user-images.githubusercontent.com/53115461/130040399-77a9112e-7bff-4bcd-9b0e-e76b4ca62f89.png)

2. line drawn at floor height on the location of body
![image](https://user-images.githubusercontent.com/53115461/130040422-4a233936-7cac-4512-b09e-1ef46cea67ba.png)

In trying to align my coordinates with the coordinates of the line (see log in screenshot) I have also noticed that **even when the coordinates match up, the visual representation does not.**

**Comment by niebl** [comment]
I have a theory: consider the floor in the following screenshot
![image](https://user-images.githubusercontent.com/53115461/130041209-38ef7f11-d440-44fd-bd6e-6ba1af1eb7eb.png)

I now tilt the sensor downwards by a few degrees:
![image](https://user-images.githubusercontent.com/53115461/130041422-b3f56efc-313c-4aff-b64f-09fdd319cffe.png)

As you can see, the detected floor is adjusted by the kinect.
My theory would be that the body position is relative to this adjusted floor while the drawn line is in relation to the true camera-space.
However I have not yet confirmed that hypothesis. Some research into the documentation may be needed.

**Comment by niebl** [comment]
In the meantime, a more sensible approach would be to drop the method of drawing a line and instead use the body coordinates to let the user define the passageway.
This could possibly be implemented the following way:
1. Stand right in front of the entry end press the button "outside". The position is saved in a variable.
2. Walk through the entry and press the button "inside". This position is also saved in a variable.
3. Using the Body positions the program will now define the threshold of the entryway as a line attached to the line between the two points, which is perpendicular to the line between the two points (see illustration). Or more comprehensively phrased: a line separating the two points at the middlepoint between them
![image](https://user-images.githubusercontent.com/53115461/130042677-7a33b5df-df07-41ca-9c82-8b8a5588787a.png)

This would be a fix that can avoid the Problem of this issue. However it would come with the cost that it will require two people to define an entryway, one person that presses the button and another one that stands in the location of the points to record.
I think this is a compromise I would be willing to make.

**Comment by niebl** [comment]
![image](https://user-images.githubusercontent.com/53115461/130232216-475d163f-bff3-418f-8099-a2b4ff4bf64d.png)

I implemented a very crude solution in PSS_alternative, where two points "inside" and "outside" are recorded by click of a button, with the threshold being calculated by drawing a line between those two points and rotating it 90° Clockwise.

This solution does not yet pass the line over to the next window, that would be a TODO.

If we can not figure out what is causing the issue mentioned above, I propose we keep working with this alternative solution.

**Comment by violetasdev** [comment]
Hi Max and Felix, 
I was experimenting with the code today, and here are the findings.

My setup is sitting in the office, with a thermo-black-bottle no reflective and a 2.00 meters wood ruler. I want to measure the distance from the Kinect to the bottle. With the camera standing frontal to the scene. 

First, I wanted to check if the depth values are being correctly gathered in the GetZ method. For that, I created some code showing the value of the depth data after saving the data and before changing the screen as we don't know the last frame.

```
int posy=Convert.ToInt16(p.Y);
int posx = Convert.ToInt16(p.X);
Console.WriteLine($"x is {posx}");
Console.WriteLine($"y is { posy}");
ShowDepthFrame(posx,posy, depthFrame);

```
It will add to the ___ShodeDepthFrame___ an output message to check the depth value. Remember:

1. We have a vector with all the values. Then, to get the value in the position (x,y), we must have multiple times the **depthFrameDescription.Width**. For now, we know it is 512.
2. The depth information is in mm, so we need to transform that to meters to understand it better

```
//Only if you have a valid stroke, show me the value on that point:
           if (x > 0) {
                Console.WriteLine("Calculate Depth");
                Console.WriteLine($"depth is {(frameData[x + (y * 512)])/1000.00 } raw: {(frameData[x + (y * 512)])}");
            }
```

If we compare the values from the GetZ and this, we get:

![Screenshot 2021-08-23 164706](https://user-images.githubusercontent.com/3913942/130470192-87d94781-52cb-40a5-9e8f-348a52072f42.png)

**From the image, the coordinates X and Y are in canvas space, whereas the Depth value is in real-world space (green lines).**  I suggest finding a way to transform them. The blackest line is a ruler that I use to take measurements. The calculated distance is correct with a small margin of error. Here is the evidence:

![photo_2021-08-23_17-04-47](https://user-images.githubusercontent.com/3913942/130471148-ed17664f-6b47-449f-a591-ffe0ae4918cd.jpg)

With more tests, you can see the variation of the distance, which is not too large. You have to decide on that:
![Screenshot 2021-08-23 164749](https://user-images.githubusercontent.com/3913942/130470191-f184f86b-af41-41bd-9e4a-13d523f04e44.png)

![Screenshot 2021-08-23 164845](https://user-images.githubusercontent.com/3913942/130470194-ca7b3be5-13f2-44e1-a9b5-6f7034418e88.png)
![Screenshot 2021-08-23 164808](https://user-images.githubusercontent.com/3913942/130470197-e6a8bc30-0336-4b6f-8f69-98dea067695c.png)

The correction you need to apply is from the real-world distance to the canvas space. You can already see a correction in the visualization as the line is similar to my body. 

![Screenshot 2021-08-23 172019](https://user-images.githubusercontent.com/3913942/130473256-4e6d3c46-99cd-43ea-8a95-8c498315a312.png)

If we know the Canvas Height from the FrameDescription object, and we know that the maximum distance of view of the Kinect is ~ 4.5 meters, it is possible to transform the value of the Depth to your canvas space.

```
            myLine.X1 = points[0, 0];
            myLine.X2 = points[1, 0];
           
            Console.WriteLine($"l1 x: {points[0, 0]} l1 y: {points[0, 2]}");

            myLine.Y1 = fieldOfView.ActualHeight-(fieldOfView.ActualHeight*points[0,2])/4.5;
            myLine.Y2 = fieldOfView.ActualHeight-(fieldOfView.ActualHeight*points[1,2])/4.5;

            Console.WriteLine($"l1 corrected x: {myLine.X1} l1 y: {myLine.Y1}");
            Console.WriteLine($"l2 corrected x: {myLine.X2} l2 y: {myLine.Y2}");
```
Output:

```
l1 x: 309,111111111111 l1 y: 1,196
l1 corrected x: 309,111111111111 l1 y: 311,310222222222
l2 corrected x: 314,444444444444 l2 y: 312,252444444444
ellipse x: 220,253284835815 ellipse y: 105,01709690094

```
 
I hope this insight into what is happening helps you to get inspired. I am sure you can come up with a cleaner solution ^^ 

I created a branch with all the modifications if you want to check them out. 

PS. Remember that the body coordinates are mirrored in the Kinect ;)
PS2. The output can be large as it is per depth frame. 
PS3. It would be nice to add labels to your text field for the second window.

**Comment by niebl** [comment]
![image](https://user-images.githubusercontent.com/53115461/130603716-f6ad4588-70ff-492b-84b5-a64656c50f69.png)
Max tried it out and the depth is accurate. We know have the challenge of having to convert the x coordinate from canvas space to camera space.
We discussed a possible solution with the help of a sketch. Forgive the crude MSPaint quality.
since we already know `x` in canvas space, as well as the depth `d` of the point to the camera, it is possible to calculate the angle `alpha` using the known resolution `breite` and FOV `FoV` of the kinect depth Sensor.
Since the origin of the camera is in the middle, we need to half both of these constants, as well as adjusting `x_c` so it has it's own origin at the center

The solution should be `x = sin( (x_c / 256) * 35.3) * d`

**Comment by xamton17** [comment]
![grafik](https://user-images.githubusercontent.com/66955751/130604810-f03b1270-ce5a-4d54-a0b4-35910cd2a360.png)
 i tried it with this calculation but the result is still not correct.
![grafik](https://user-images.githubusercontent.com/66955751/130604905-62bc9491-fb1c-43af-a747-fdf7443241a5.png)

**Comment by xamton17** [comment]
previously, in  mainWindow getZ used the value of depthFrameData, despite us using mapdepthFrametocameraspace.
we changed it so it would extract the z-value from the csp object. To adjust the scale from CameraSpacePOint to Real World Coordinates we changed the scaling factor.

We although changed the function to get the x coordinate, before it simply took the x value of the given StylusPoint: return stylusPoint.X
Now we work here with the CameraSpacePoint ,too.
![grafik](https://user-images.githubusercontent.com/66955751/130615783-ea53bcd6-3642-42a7-b789-e28f493c1b29.png)

The result works for our system, no line was set outside of the monitoring triangle like in the post above.

There is still a little problem with the body coordinates in relation to the line coordinates:

![grafik](https://user-images.githubusercontent.com/66955751/130616240-f86d36ee-f715-431c-8c87-24e2d02e7960.png)

here we can see (from top to bottom) X1, X2 , Y1, Y2 of the line in the textboxes and the last two are the x and y coordinates of the body, you can see that there is a difference between them even though the body is standing right on the line. And in the left topside corner are the body coordinates aswell which are  different aswell.
